const ARMADURAS = [
  // ───────── ARMADURAS LEVES ─────────
  {
    id: "acolchoado",
    nome: "Acolchoada",
    categoria: "Leve",
    custo: "5 PO",
    caFormula: "11 + Modificador de Destreza",
    caBase: 11,
    usaModDes: true,
    limiteModDes: null,
    forcaMin: null,
    furtividade: "Desvantagem",
    peso: "4 kg",
    descricao:
      "Camadas estofadas de tecido e forro. Oferece proteção leve com boa mobilidade.",
  },
  {
    id: "couro",
    nome: "Couro",
    categoria: "Leve",
    custo: "10 PO",
    caFormula: "11 + Modificador de Destreza",
    caBase: 11,
    usaModDes: true,
    limiteModDes: null,
    forcaMin: null,
    furtividade: "Normal",
    peso: "5 kg",
    descricao:
      "Peitoral e ombreiras de couro curtido em óleo, com partes flexíveis.",
  },
  {
    id: "couro-batido",
    nome: "Couro Batido",
    categoria: "Leve",
    custo: "45 PO",
    caFormula: "12 + Modificador de Destreza",
    caBase: 12,
    usaModDes: true,
    limiteModDes: null,
    forcaMin: null,
    furtividade: "Normal",
    peso: "7 kg",
    descricao:
      "Couro rígido reforçado com rebites ou cravos, oferecendo proteção extra.",
  },

  // ───────── ARMADURAS MÉDIAS ─────────
  {
    id: "gibao-peles",
    nome: "Gibão de Peles",
    categoria: "Média",
    custo: "10 PO",
    caFormula: "12 + Modificador de Des (máx. +2)",
    caBase: 12,
    usaModDes: true,
    limiteModDes: 2,
    forcaMin: null,
    furtividade: "Normal",
    peso: "6 kg",
    descricao:
      "Peles e couros grossos, comuns em tribos bárbaras e povos com pouco acesso a metal.",
  },
  {
    id: "cota-malha-parcial",
    nome: "Cota de Malha Parcial",
    categoria: "Média",
    custo: "50 PO",
    caFormula: "13 + Modificador de Des (máx. +2)",
    caBase: 13,
    usaModDes: true,
    limiteModDes: 2,
    forcaMin: null,
    furtividade: "Normal",
    peso: "10 kg",
    descricao:
      "Camisão de anéis de metal usado sob tecido ou couro, cobrindo a parte superior do corpo.",
  },
  {
    id: "lorica-escamas",
    nome: "Lórica de Escamas",
    categoria: "Média",
    custo: "50 PO",
    caFormula: "14 + Modificador de Des (máx. +2)",
    caBase: 14,
    usaModDes: true,
    limiteModDes: 2,
    forcaMin: null,
    furtividade: "Desvantagem",
    peso: "22 kg",
    descricao:
      "Casaco e perneiras cobertos com placas de metal em formato de escamas.",
  },
  {
    id: "peitoral",
    nome: "Couraça Peitoral",
    categoria: "Média",
    custo: "400 PO",
    caFormula: "14 + Modificador de Des (máx. +2)",
    caBase: 14,
    usaModDes: true,
    limiteModDes: 2,
    forcaMin: null,
    furtividade: "Normal",
    peso: "10 kg",
    descricao:
      "Peça de metal que protege o peito, deixando braços e pernas mais livres.",
  },
  {
    id: "placas-parcial",
    nome: "Placas Parcial",
    categoria: "Média",
    custo: "750 PO",
    caFormula: "15 + Modificador de Des (máx. +2)",
    caBase: 15,
    usaModDes: true,
    limiteModDes: 2,
    forcaMin: null,
    furtividade: "Desvantagem",
    peso: "20 kg",
    descricao:
      "Placas de metal que cobrem a maior parte do corpo, sem proteção total das pernas.",
  },

  // ───────── ARMADURAS PESADAS ─────────
  {
    id: "cota-aneis",
    nome: "Cota de Anéis",
    categoria: "Pesada",
    custo: "30 PO",
    caFormula: "14 (não usa Des)",
    caBase: 14,
    usaModDes: false,
    limiteModDes: null,
    forcaMin: null,
    furtividade: "Desvantagem",
    peso: "20 kg",
    descricao:
      "Couro reforçado com anéis metálicos costurados, inferior à cota de malha.",
  },
  {
    id: "cota-malha",
    nome: "Cota de Malha",
    categoria: "Pesada",
    custo: "75 PO",
    caFormula: "16 (não usa Des)",
    caBase: 16,
    usaModDes: false,
    limiteModDes: null,
    forcaMin: 13,
    furtividade: "Desvantagem",
    peso: "27 kg",
    descricao:
      "Anéis de metal interligados sobre acolchoamento, inclui manoplas.",
  },
  {
    id: "cota-talas",
    nome: "Cota de Talas",
    categoria: "Pesada",
    custo: "200 PO",
    caFormula: "17 (não usa Des)",
    caBase: 17,
    usaModDes: false,
    limiteModDes: null,
    forcaMin: 15,
    furtividade: "Desvantagem",
    peso: "30 kg",
    descricao:
      "Tiras verticais de metal rebitadas em couro sobre malha flexível.",
  },
  {
    id: "placas",
    nome: "Placas",
    categoria: "Pesada",
    custo: "1.500 PO",
    caFormula: "18 (não usa Des)",
    caBase: 18,
    usaModDes: false,
    limiteModDes: null,
    forcaMin: 15,
    furtividade: "Desvantagem",
    peso: "32 kg",
    descricao:
      "Placas de metal que cobrem todo o corpo; máxima proteção para guerreiros treinados.",
  },

  // ───────── ESCUDO ─────────
  {
    id: "escudo",
    nome: "Escudo",
    categoria: "Escudo",
    custo: "10 PO",
    caFormula: "+2 CA",
    caBase: 2,
    usaModDes: false,
    limiteModDes: null,
    forcaMin: null,
    furtividade: "Normal",
    peso: "3 kg",
    descricao: "Escudo padrão que concede +2 à Classe de Armadura.",
  },

  // opção "sem armadura"
  {
    id: "nenhuma",
    nome: "Sem armadura",
    categoria: "Nenhuma",
    custo: "—",
    caFormula: "10 + Modificador de Des (regra padrão)",
    caBase: 10,
    usaModDes: true,
    limiteModDes: null,
    forcaMin: null,
    furtividade: "Normal",
    peso: "—",
    descricao: "Roupas comuns ou sem proteção de armadura.",
  },
];

export default ARMADURAS;