/**
 * Base de Dados Estruturada de Traços Raciais e Recursos de Classe de D&D 5e
 * Arquivo: src/Array/HabilidadesDB.js
 */

export const ACTION_TYPES = {
  PASSIVA: { label: "Passiva", color: "#78909c", bg: "rgba(120, 144, 156, 0.15)", border: "rgba(120, 144, 156, 0.4)" },
  ACAO: { label: "1 Ação", color: "#e53935", bg: "rgba(229, 57, 53, 0.15)", border: "rgba(229, 57, 53, 0.4)" },
  ACAO_BONUS: { label: "Ação Bônus", color: "#fb8c00", bg: "rgba(251, 140, 0, 0.15)", border: "rgba(251, 140, 0, 0.4)" },
  REACAO: { label: "Reação", color: "#ffd600", bg: "rgba(255, 214, 0, 0.18)", border: "rgba(255, 214, 0, 0.45)" },
  ESPECIAL: { label: "Especial", color: "#ab47bc", bg: "rgba(171, 71, 188, 0.15)", border: "rgba(171, 71, 188, 0.4)" },
};

export const RECHARGE_TYPES = {
  ILIMITADO: "Ilimitado",
  DESCANSO_CURTO: "Descanso Curto",
  DESCANSO_LONGO: "Descanso Longo",
  DESCANSO_CURTO_LONGO: "Descanso Curto ou Longo",
  CARGAS: "Cargas",
  ESPECIAL: "Especial",
  NENHUM: "Nenhum",
};

export function getActionTypeStyle(tipoAcao) {
  const norm = String(tipoAcao || "").toLowerCase().trim();
  if (norm.includes("bônus") || norm.includes("bonus")) return ACTION_TYPES.ACAO_BONUS;
  if (norm.includes("reação") || norm.includes("reacao")) return ACTION_TYPES.REACAO;
  if (norm.includes("especial")) return ACTION_TYPES.ESPECIAL;
  if (norm.includes("ação") || norm.includes("acao") || norm === "1 ação" || norm === "acao") return ACTION_TYPES.ACAO;
  return ACTION_TYPES.PASSIVA;
}

export function normalizeString(str) {
  if (!str) return "";
  return String(str)
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .trim();
}

// ==========================================
// 🧬 TRAÇOS RACIAIS E SUB-RACIAIS (D&D 5e)
// ==========================================
export const HABILIDADES_RACIAIS = [
  // --- ANÃO & SUB-RAÇAS ---
  {
    id: "raca_anao_visao_escuro",
    nome: "Visão no Escuro (Anão)",
    categoria: "raca",
    vinculo: "Anão",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse penumbra (tons de cinza).",
  },
  {
    id: "raca_anao_resiliencia",
    nome: "Resiliência Anã",
    categoria: "raca",
    vinculo: "Anão",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Vantagem em testes de resistência contra venenos e resistência contra dano de veneno.",
  },
  {
    id: "raca_anao_treinamento_combate",
    nome: "Treinamento Anão em Combate",
    categoria: "raca",
    vinculo: "Anão",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Proficiência com machados de batalha, machadinhas, martelos leves e martelos de guerra.",
  },
  {
    id: "raca_anao_especializacao_rochas",
    nome: "Especialização em Rochas",
    categoria: "raca",
    vinculo: "Anão",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Adiciona o dobro do bônus de proficiência em testes de Inteligência (História) sobre a origem de trabalhos em pedra.",
  },
  {
    id: "subraca_anao_colina_tenacidade",
    nome: "Tenacidade Anã",
    categoria: "subraca",
    vinculo: "Anão da Colina",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Seu máximo de pontos de vida aumenta em 1, e aumenta em mais 1 a cada nível subsequente.",
  },
  {
    id: "subraca_anao_montanha_armaduras",
    nome: "Treinamento Anão com Armaduras",
    categoria: "subraca",
    vinculo: "Anão da Montanha",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Proficiência com armaduras leves e armaduras médias.",
  },

  // --- ELFO & SUB-RAÇAS ---
  {
    id: "raca_elfo_visao_escuro",
    nome: "Visão no Escuro (Elfo)",
    categoria: "raca",
    vinculo: "Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como penumbra (tons de cinza).",
  },
  {
    id: "raca_elfo_sentidos_agucados",
    nome: "Sentidos Aguçados",
    categoria: "raca",
    vinculo: "Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Proficiência na perícia Percepção.",
  },
  {
    id: "raca_elfo_ancestral_feerico",
    nome: "Ancestral Feérico",
    categoria: "raca",
    vinculo: "Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Vantagem em testes de resistência contra ser enfeitiçado e imunidade mágica ao sono.",
  },
  {
    id: "raca_elfo_transe",
    nome: "Transe",
    categoria: "raca",
    vinculo: "Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Descanso Longo",
    usosMax: null,
    descricao: "Não precisa dormir; medita profundamente semiconsciente durante 4 horas para obter os benefícios de 8 horas de repouso.",
  },
  {
    id: "subraca_alto_elfo_truque",
    nome: "Truque Adicional (Alto Elfo)",
    categoria: "subraca",
    vinculo: "Alto Elfo",
    nivel: 1,
    tipoAcao: "Especial",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Conhece 1 truque da lista de magias de Mago (usa Inteligência como atributo de conjuração).",
  },
  {
    id: "subraca_alto_elfo_treinamento_armas",
    nome: "Treinamento Élfico em Armas (Alto Elfo)",
    categoria: "subraca",
    vinculo: "Alto Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Proficiência com espadas longas, espadas curtas, arcos curtos e arcos longos.",
  },
  {
    id: "subraca_elfo_floresta_pes_ligeiros",
    nome: "Pés Ligeiros",
    categoria: "subraca",
    vinculo: "Elfo da Floresta",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Seu deslocamento base de caminhada aumenta para 10,5 metros.",
  },
  {
    id: "subraca_elfo_floresta_mascara_natureza",
    nome: "Máscara da Natureza",
    categoria: "subraca",
    vinculo: "Elfo da Floresta",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Pode tentar se esconder mesmo quando estiver apenas levemente obscurecido por folhagem, chuva forte, neve ou névoa.",
  },
  {
    id: "subraca_drow_magia",
    nome: "Magia Drow",
    categoria: "subraca",
    vinculo: "Drow",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Descanso Longo",
    usosMax: 1,
    descricao: "Conhece o truque Globos de Luz. No 3º nível conjura Fogo das Fadas (1x/dia); no 5º nível conjura Escuridão (1x/dia). Usa Carisma.",
  },

  // --- HALFLING & SUB-RAÇAS ---
  {
    id: "raca_halfling_sortudo",
    nome: "Sortudo",
    categoria: "raca",
    vinculo: "Halfling",
    nivel: 1,
    tipoAcao: "Reação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Ao rolar um 1 natural em um d20 em jogada de ataque, teste de habilidade ou teste de resistência, pode rerrolar e usar o novo resultado.",
  },
  {
    id: "raca_halfling_bravura",
    nome: "Bravura",
    categoria: "raca",
    vinculo: "Halfling",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Vantagem em testes de resistência contra ficar amedrontado.",
  },
  {
    id: "raca_halfling_agilidade",
    nome: "Agilidade Halfling",
    categoria: "raca",
    vinculo: "Halfling",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Pode mover-se através do espaço de qualquer criatura que seja de tamanho maior que o seu.",
  },
  {
    id: "subraca_halfling_furtividade_natural",
    nome: "Furtividade Natural",
    categoria: "subraca",
    vinculo: "Pés Leves",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Pode tentar se esconder mesmo quando estiver ocultado apenas por uma criatura que for pelo menos um tamanho maior que você.",
  },
  {
    id: "subraca_halfling_resiliencia_robusto",
    nome: "Resiliência dos Robustos",
    categoria: "subraca",
    vinculo: "Robusto",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Vantagem em testes de resistência contra veneno e resistência contra dano de veneno.",
  },

  // --- HUMANO & VARIANTE ---
  {
    id: "raca_humano_versatilidade",
    nome: "Versatilidade Humana",
    categoria: "raca",
    vinculo: "Humano",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Todos os seus seis valores de atributo aumentam em +1 (ou variante com talento e perícia adicional).",
  },
  {
    id: "subraca_humano_variante_talento",
    nome: "Talento Inicial (Humano Variante)",
    categoria: "subraca",
    vinculo: "Humano Variante",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Ganha um Talento à sua escolha no 1º nível e proficiência em 1 perícia adicional.",
  },

  // --- DRACONATO ---
  {
    id: "raca_draconato_sopro",
    nome: "Arma de Sopro",
    categoria: "raca",
    vinculo: "Draconato",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Descanso Curto",
    usosMax: 1,
    descricao: "Exala energia destrutiva conforme ancestral dracônico (Linha de 9m ou Cone de 4,5m). Causa 2d6 no 1º nível, 3d6 no 6º, 4d6 no 11º e 5d6 no 16º nível.",
  },
  {
    id: "raca_draconato_resistencia",
    nome: "Resistência Dracônica",
    categoria: "raca",
    vinculo: "Draconato",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Resistência ao tipo de dano associado ao seu ancestral dracônico.",
  },

  // --- GNOMO & SUB-RAÇAS ---
  {
    id: "raca_gnomo_esperteza",
    nome: "Esperteza Gnômica",
    categoria: "raca",
    vinculo: "Gnomo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Vantagem em todos os testes de resistência de Inteligência, Sabedoria e Carisma contra magia.",
  },
  {
    id: "raca_gnomo_visao_escuro",
    nome: "Visão no Escuro (Gnomo)",
    categoria: "raca",
    vinculo: "Gnomo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse penumbra.",
  },
  {
    id: "subraca_gnomo_falar_bestas",
    nome: "Falar com Bestas Pequenas",
    categoria: "subraca",
    vinculo: "Gnomo da Floresta",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Através de sons e gestos, comunica ideias simples para bestas Pequenas ou menores.",
  },
  {
    id: "subraca_gnomo_ilusionista_natural",
    nome: "Ilusionista Natural",
    categoria: "subraca",
    vinculo: "Gnomo da Floresta",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Conhece o truque Ilusão Menor (usa Inteligência como habilidade de conjuração).",
  },
  {
    id: "subraca_gnomo_engenhoqueiro",
    nome: "Engenhoqueiro",
    categoria: "subraca",
    vinculo: "Gnomo das Rochas",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Especial",
    usosMax: 3,
    descricao: "Pode gastar 1h e 10 po para criar mecanismos Miúdos (Brinquedo Mecânico, Isqueiro Mecânico ou Caixa de Música).",
  },
  {
    id: "subraca_gnomo_conhecimento_artifice",
    nome: "Conhecimento de Artífice",
    categoria: "subraca",
    vinculo: "Gnomo das Rochas",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Adiciona o dobro do bônus de proficiência em testes de História sobre itens mágicos, objetos alquímicos e dispositivos tecnológicos.",
  },

  // --- MEIO-ELFO ---
  {
    id: "raca_meio_elfo_visao_escuro",
    nome: "Visão no Escuro (Meio-Elfo)",
    categoria: "raca",
    vinculo: "Meio-Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse penumbra.",
  },
  {
    id: "raca_meio_elfo_ancestral_feerico",
    nome: "Ancestral Feérico (Meio-Elfo)",
    categoria: "raca",
    vinculo: "Meio-Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Vantagem em testes de resistência contra ser enfeiticado e magia não pode colocá-lo para dormir.",
  },
  {
    id: "raca_meio_elfo_versatilidade_pericias",
    nome: "Versatilidade em Perícias",
    categoria: "raca",
    vinculo: "Meio-Elfo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Proficiência em duas perícias à sua escolha.",
  },

  // --- MEIO-ORC ---
  {
    id: "raca_meio_orc_resistencia_implacavel",
    nome: "Resistência Implacável",
    categoria: "raca",
    vinculo: "Meio-Orc",
    nivel: 1,
    tipoAcao: "Reação",
    recarga: "Descanso Longo",
    usosMax: 1,
    descricao: "Ao ser reduzido a 0 pontos de vida sem morrer instantaneamente, pode voltar para 1 ponto de vida no lugar.",
  },
  {
    id: "raca_meio_orc_ataques_selvagens",
    nome: "Ataques Selvagens",
    categoria: "raca",
    vinculo: "Meio-Orc",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Em um acerto crítico com arma corpo a corpo, rola um dado de dano adicional da arma e o soma ao total.",
  },
  {
    id: "raca_meio_orc_ameacador",
    nome: "Ameaçador",
    categoria: "raca",
    vinculo: "Meio-Orc",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Ganha proficiência na perícia Intimidação.",
  },

  // --- TIEFLING ---
  {
    id: "raca_tiefling_visao_escuro",
    nome: "Visão no Escuro (Tiefling)",
    categoria: "raca",
    vinculo: "Tiefling",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Enxerga na penumbra a até 18 metros como se fosse luz plena, e no escuro como se fosse penumbra.",
  },
  {
    id: "raca_tiefling_resistencia_infernal",
    nome: "Resistência Infernal",
    categoria: "raca",
    vinculo: "Tiefling",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Possui resistência a dano de fogo.",
  },
  {
    id: "raca_tiefling_legado_infernal",
    nome: "Legado Infernal",
    categoria: "raca",
    vinculo: "Tiefling",
    nivel: 1,
    tipoAcao: "Especial",
    recarga: "Descanso Longo",
    usosMax: 1,
    descricao: "Conhece Taumaturgia. No 3º nível conjura Repreensão Infernal (2º nível, 1x/dia); no 5º nível conjura Escuridão (1x/dia). Usa Carisma.",
  },
];

// ==========================================
// ⚔️ RECURSOS DE CLASSE (D&D 5e NÍVEIS 1 A 20)
// ==========================================
export const HABILIDADES_CLASSES = [
  // --- BÁRBARO ---
  {
    id: "barbaro_furia",
    nome: "Fúria",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 1,
    tipoAcao: "Ação Bônus",
    recarga: "Descanso Longo",
    usosMax: "TABELA_FURIA",
    descricao: "Dura 1 min. Vantagem em testes e resistências de Força, bônus de dano de fúria (+2 a +4) e resistência a dano de concussão, cortante e perfurante.",
  },
  {
    id: "barbaro_defesa_sem_armadura",
    nome: "Defesa sem Armadura (Bárbaro)",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Sem armadura, sua CA é igual a 10 + Modificador de Destreza + Modificador de Constituição (permite escudo).",
  },
  {
    id: "barbaro_ataque_descuidado",
    nome: "Ataque Descuidado",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 2,
    tipoAcao: "Especial",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "No primeiro ataque do turno, ganha vantagem em ataques corpo a corpo com Força, mas ataques contra você têm vantagem até o início do seu próximo turno.",
  },
  {
    id: "barbaro_sentido_perigo",
    nome: "Sentido de Perigo",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 2,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Vantagem em testes de resistência de Destreza contra armadilhas e magias que possa ver.",
  },
  {
    id: "barbaro_ataque_extra",
    nome: "Ataque Extra (Bárbaro)",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Pode atacar duas vezes sempre que realizar a ação de Ataque no seu turno.",
  },
  {
    id: "barbaro_movimento_rapido",
    nome: "Movimento Rápido",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Seu deslocamento aumenta em +3 metros enquanto não estiver vestindo armadura pesada.",
  },
  {
    id: "barbaro_critico_brutal",
    nome: "Crítico Brutal",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 9,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Rola +1 dado de dano adicional em acertos críticos corpo a corpo (+2 dados no 13º e +3 dados no 17º nível).",
  },
  {
    id: "barbaro_furia_implacavel",
    nome: "Fúria Implacável",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 11,
    tipoAcao: "Reação",
    recarga: "Descanso Curto",
    usosMax: "ESPECIAL",
    descricao: "Ao cair para 0 PV em fúria sem morrer, teste Con CD 10 para voltar a 1 PV (CD aumenta em +5 a cada uso até descansar).",
  },
  {
    id: "barbaro_furia_persistente",
    nome: "Fúria Persistente",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 15,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Sua fúria é tão intensa que ela só termina precocemente se você cair inconsciente ou se você decidir encerrá-la.",
  },
  {
    id: "barbaro_forca_indomavel",
    nome: "Força Indomável",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 18,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Se o total de um teste de Força for menor que seu valor de Força, você pode usar seu valor de Força no lugar do resultado.",
  },
  {
    id: "barbaro_campeao_primordial",
    nome: "Campeão Primordial",
    categoria: "classe",
    vinculo: "Bárbaro",
    nivel: 20,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Seus valores de Força e Constituição aumentam em +4 cada, e seu valor máximo para esses atributos se torna 24.",
  },

  // --- BARDO ---
  {
    id: "bardo_inspiracao",
    nome: "Inspiração de Bardo",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 1,
    tipoAcao: "Ação Bônus",
    recarga: "Descanso Longo",
    usosMax: "MOD_CAR",
    descricao: "Gera um dado (d6 no 1º, d8 no 5º, d10 no 10º, d12 no 15º) para um aliado a até 18m somar em 1 ataque, teste ou salvaguarda nos próximos 10 minutos.",
  },
  {
    id: "bardo_conjuracao",
    nome: "Conjuração de Bardo",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Capacidade de conjurar magias da lista de bardo utilizando Carisma como atributo de conjuração.",
  },
  {
    id: "bardo_versatilidade",
    nome: "Versatilidade (Jack of All Trades)",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 2,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Adiciona metade do seu bônus de proficiência (arredondado para baixo) em qualquer teste de atributo que não seja proficiente.",
  },
  {
    id: "bardo_cancao_descanso",
    nome: "Canção de Descanso",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 2,
    tipoAcao: "Passiva",
    recarga: "Descanso Curto",
    usosMax: null,
    descricao: "Aliados que recuperarem PV gastando Dados de Vida no descanso curto ganham +1d6 PV extras (+1d8 no 9º, +1d10 no 13º, +1d12 no 17º).",
  },
  {
    id: "bardo_especializacao",
    nome: "Especialização (Bardo)",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 3,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Escolha duas de suas perícias proficientes. Seu bônus de proficiência é dobrado para qualquer teste de atributo que você fizer usando qualquer uma das perícias escolhidas (mais 2 no nível 10).",
  },
  {
    id: "bardo_fonte_inspiracao",
    nome: "Fonte de Inspiração",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você agora recupera todos os usos gastos da sua Inspiração de Bardo após terminar um descanso curto ou longo.",
  },
  {
    id: "bardo_cancao_protecao",
    nome: "Canção de Proteção",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 6,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Inicia atuação até o fim do próximo turno concedendo vantagem em testes contra medo e encantamento para aliados a até 9 metros.",
  },
  {
    id: "bardo_segredos_magicos",
    nome: "Segredos Mágicos",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 10,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Aprende 2 magias de qualquer classe nos níveis 10, 14 e 18, contando como magias de bardo.",
  },
  {
    id: "bardo_inspiracao_superior",
    nome: "Inspiração Superior",
    categoria: "classe",
    vinculo: "Bardo",
    nivel: 20,
    tipoAcao: "Passiva",
    recarga: "Especial",
    usosMax: null,
    descricao: "Quando você rolar iniciativa e não tiver nenhum uso de Inspiração de Bardo restante, você recupera um uso.",
  },

  // --- GUERREIRO ---
  {
    id: "guerreiro_estilo_luta",
    nome: "Estilo de Luta (Guerreiro)",
    categoria: "classe",
    vinculo: "Guerreiro",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você adota um estilo de combate particular (Arquearia, Defesa, Duelo, Luta com Duas Armas, Proteção ou Luta com Armas Grandes).",
  },
  {
    id: "guerreiro_retomar_folego",
    nome: "Retomar o Fôlego",
    categoria: "classe",
    vinculo: "Guerreiro",
    nivel: 1,
    tipoAcao: "Ação Bônus",
    recarga: "Descanso Curto",
    usosMax: 1,
    descricao: "Recupera pontos de vida equivalentes a 1d10 + nível de guerreiro.",
  },
  {
    id: "guerreiro_surto_acao",
    nome: "Surto de Ação",
    categoria: "classe",
    vinculo: "Guerreiro",
    nivel: 2,
    tipoAcao: "Especial",
    recarga: "Descanso Curto",
    usosMax: "TABELA_SURTO_ACAO",
    descricao: "Realiza uma ação adicional no seu turno além da sua ação normal e ação bônus (2 usos no nível 17).",
  },
  {
    id: "guerreiro_ataque_extra",
    nome: "Ataque Extra (Guerreiro)",
    categoria: "classe",
    vinculo: "Guerreiro",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Pode atacar duas vezes na ação de Ataque (3 vezes no nível 11, 4 vezes no nível 20).",
  },
  {
    id: "guerreiro_indomavel",
    nome: "Indomável",
    categoria: "classe",
    vinculo: "Guerreiro",
    nivel: 9,
    tipoAcao: "Reação",
    recarga: "Descanso Longo",
    usosMax: "TABELA_INDOMAVEL",
    descricao: "Permite jogar novamente um teste de resistência no qual tenha falhado, sendo obrigado a usar o novo resultado (2 no nível 13, 3 no nível 17).",
  },
  {
    id: "guerreiro_campeao_critico_aprimorado",
    nome: "Crítico Aprimorado (Campeão)",
    categoria: "subclasse",
    vinculo: "Campeão",
    nivel: 3,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Seus ataques com armas conquistam acerto crítico em rolagens de 19 e 20 no d20 (18 a 20 no nível 15).",
  },

  // --- CLÉRIGO ---
  {
    id: "clerigo_conjuracao",
    nome: "Conjuração de Clérigo",
    categoria: "classe",
    vinculo: "Clérigo",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Conjura magias divinas utilizando Sabedoria como atributo de conjuração.",
  },
  {
    id: "clerigo_canalizar_expulsar",
    nome: "Canalizar Divindade: Expulsar Mortos-Vivos",
    categoria: "classe",
    vinculo: "Clérigo",
    nivel: 2,
    tipoAcao: "1 Ação",
    recarga: "Descanso Curto",
    usosMax: "CANALIZAR_DIVINDADE",
    descricao: "Cada morto-vivo a até 9m que vir ou ouvir o símbolo sagrado faz teste de Sabedoria ou foge durante 1 minuto.",
  },
  {
    id: "clerigo_destruir_mortos_vivos",
    nome: "Destruir Mortos-Vivos",
    categoria: "classe",
    vinculo: "Clérigo",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Mortos-vivos que falharem no teste de Expulsar são instantaneamente destruídos se tiverem ND ≤ 1/2 (ND 1 no 8º, ND 2 no 11º, ND 3 no 14º, ND 4 no 17º).",
  },
  {
    id: "clerigo_intervencao_divina",
    nome: "Intervenção Divina",
    categoria: "classe",
    vinculo: "Clérigo",
    nivel: 10,
    tipoAcao: "1 Ação",
    recarga: "Descanso Longo",
    usosMax: 1,
    descricao: "Rola d100; se o resultado for ≤ ao nível de clérigo (automático no nível 20), a divindade intervém diretamente (recarga de 7 dias em caso de sucesso).",
  },

  // --- PALADINO ---
  {
    id: "paladino_sentido_divino",
    nome: "Sentido Divino",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Descanso Longo",
    usosMax: "1 + MOD_CAR",
    descricao: "Sente a localização de celestiais, corruptores e mortos-vivos ou locais/objetos consagrados/conspurcados a até 18 metros até o fim do próximo turno.",
  },
  {
    id: "paladino_cura_maos",
    nome: "Cura pelas Mãos (Lay on Hands)",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Descanso Longo",
    usosMax: "NIVEL_PALADINO * 5",
    descricao: "Reserva curativa de PVs por toque. Permite gastar 5 pontos de cura para expurgar uma doença ou neutralizar um veneno.",
  },
  {
    id: "paladino_destruicao_divina",
    nome: "Destruição Divina (Divine Smite)",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 2,
    tipoAcao: "Especial",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Ao acertar ataque corpo a corpo, gasta espaço de magia para causar +2d8 dano radiante (1º nível) +1d8 por nível acima (máx 5d8; +1d8 extra vs mortos-vivos/corruptores).",
  },
  {
    id: "paladino_saude_divina",
    nome: "Saúde Divina",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 3,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "A magia divina fluindo através de você concede imunidade total a doenças.",
  },
  {
    id: "paladino_ataque_extra",
    nome: "Ataque Extra (Paladino)",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você pode atacar duas vezes ao invés de uma sempre que realizar a ação de Ataque.",
  },
  {
    id: "paladino_aura_protecao",
    nome: "Aura de Proteção",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 6,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Concede bônus igual ao modificador de Carisma (mínimo +1) em todos os testes de resistência para você e aliados a até 3 metros (9m no nível 18).",
  },
  {
    id: "paladino_aura_coragem",
    nome: "Aura de Coragem",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 10,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você e criaturas amigáveis a até 3 metros não podem ser amedrontados enquanto você estiver consciente (9m no nível 18).",
  },
  {
    id: "paladino_destruicao_aprimorada",
    nome: "Destruição Divina Aprimorada",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 11,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Todos os seus ataques corpo a corpo com armas causam +1d8 de dano radiante adicional constante.",
  },
  {
    id: "paladino_aura_limpeza",
    nome: "Toque Purificador",
    categoria: "classe",
    vinculo: "Paladino",
    nivel: 14,
    tipoAcao: "1 Ação",
    recarga: "Descanso Longo",
    usosMax: "MOD_CAR",
    descricao: "Você pode usar sua ação para encerrar uma magia em você mesmo ou em uma criatura voluntária que você tocar.",
  },

  // --- LADINO ---
  {
    id: "ladino_especializacao",
    nome: "Especialização (Ladino)",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Seu bônus de proficiência é dobrado em duas perícias de sua escolha ou em uma perícia e ferramentas de ladrão (mais duas no nível 6).",
  },
  {
    id: "ladino_ataque_furtivo",
    nome: "Ataque Furtivo",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "1x por turno causa dano extra (+1d6 a +10d6) com arma de acuidade ou à distância se tiver vantagem ou aliado adjacente ao alvo.",
  },
  {
    id: "ladino_giria_ladroes",
    nome: "Gíria de Ladrão",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Conhece dialeto secreto misturado com jargões e sinais para deixar recados ocultos.",
  },
  {
    id: "ladino_acao_ardilosa",
    nome: "Ação Ardilosa",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 2,
    tipoAcao: "Ação Bônus",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Permite realizar as ações de Disparada, Desengajar ou Esconder como Ação Bônus em cada turno.",
  },
  {
    id: "ladino_esquiva_sobrenatural",
    nome: "Esquiva Sobrenatural",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 5,
    tipoAcao: "Reação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Reduz pela metade o dano de um ataque que o acertar disparado por um inimigo visível.",
  },
  {
    id: "ladino_evasao",
    nome: "Evasão",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 7,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Em efeitos de Destreza que causam metade do dano em sucesso, você não sofre dano se passar e apenas metade se falhar.",
  },
  {
    id: "ladino_talento_confiavel",
    nome: "Talento Confiável",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 11,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Sempre que você fizer um teste de habilidade com proficiência, trate qualquer resultado de 9 ou menor no d20 como um 10.",
  },
  {
    id: "ladino_sentido_cego",
    nome: "Sentido Cego",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 14,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Se você puder ouvir, você fica ciente da localização de qualquer criatura escondida ou invisível a até 3 metros de você.",
  },
  {
    id: "ladino_mente_escorregadia",
    nome: "Mente Escorregadia",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 15,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você adquire proficiência em testes de resistência de Sabedoria.",
  },
  {
    id: "ladino_elusivo",
    nome: "Elusivo",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 18,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Nenhuma jogada de ataque tem vantagem contra você enquanto você não estiver incapacitado.",
  },
  {
    id: "ladino_golpe_de_sorte",
    nome: "Golpe de Sorte",
    categoria: "classe",
    vinculo: "Ladino",
    nivel: 20,
    tipoAcao: "Especial",
    recarga: "Descanso Curto",
    usosMax: 1,
    descricao: "Se errar um ataque, pode transformar o erro em um acerto. Se falhar em um teste de habilidade, pode tratar a rolagem como um 20 natural.",
  },

  // --- DRUIDA ---
  {
    id: "druida_druidico",
    nome: "Druídico",
    categoria: "classe",
    vinculo: "Druida",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você conhece o Druídico, a linguagem secreta dos druidas.",
  },
  {
    id: "druida_conjuracao",
    nome: "Conjuração de Druida",
    categoria: "classe",
    vinculo: "Druida",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Capacidade de conjurar magias divinas da natureza utilizando Sabedoria como atributo de conjuração.",
  },
  {
    id: "druida_forma_selvagem",
    nome: "Forma Selvagem",
    categoria: "classe",
    vinculo: "Druida",
    nivel: 2,
    tipoAcao: "1 Ação",
    recarga: "Descanso Curto",
    usosMax: "TABELA_FORMA_SELVAGEM",
    descricao: "Assume magicamente a forma de uma besta conhecida por até (Nível/2) horas, adotando seus PVs, CA e estatísticas físicas.",
  },
  {
    id: "druida_corpo_atemporal",
    nome: "Corpo Atemporal",
    categoria: "classe",
    vinculo: "Druida",
    nivel: 18,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Para cada 10 anos que passarem, seu corpo envelhece apenas 1 ano, e você não pode sofrer envelhecimento mágico.",
  },
  {
    id: "druida_magia_bestial",
    nome: "Magia Bestial",
    categoria: "classe",
    vinculo: "Druida",
    nivel: 18,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você pode conjurar muitas de suas magias de druida enquanto estiver em Forma Selvagem.",
  },
  {
    id: "druida_arquidruida",
    nome: "Arquidruida",
    categoria: "classe",
    vinculo: "Druida",
    nivel: 20,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você pode usar sua Forma Selvagem um número ilimitado de vezes, e ignora componentes verbais, somáticos e materiais sem custo.",
  },

  // --- MONGE ---
  {
    id: "monge_defesa_sem_armadura",
    nome: "Defesa sem Armadura (Monge)",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Sem armadura e sem escudo, sua CA é igual a 10 + Modificador de Destreza + Modificador de Sabedoria.",
  },
  {
    id: "monge_artes_marciais",
    nome: "Artes Marciais",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Permite usar Destreza para ataques desarmados/armas de monge, dado de dano marcial escalável (d4 a d10) e golpe desarmado com Ação Bônus.",
  },
  {
    id: "monge_chi",
    nome: "Energia Chi",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 2,
    tipoAcao: "Especial",
    recarga: "Descanso Curto",
    usosMax: "PONTOS_CHI",
    descricao: "Reserva mística de Chi igual ao nível de monge para alimentar habilidades (Rajada de Golpes, Defesa Paciente, Passo do Vento).",
  },
  {
    id: "monge_rajada_golpes",
    nome: "Rajada de Golpes (Chi)",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 2,
    tipoAcao: "Ação Bônus",
    recarga: "Descanso Curto",
    usosMax: "PONTOS_CHI",
    descricao: "Gasta 1 ponto de Chi imediatamente após a ação de Ataque para desferir 2 golpes desarmados com Ação Bônus.",
  },
  {
    id: "monge_defesa_paciente",
    nome: "Defesa Paciente",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 2,
    tipoAcao: "Ação Bônus",
    recarga: "Descanso Curto",
    usosMax: "PONTOS_CHI",
    descricao: "Gasta 1 ponto de Chi para realizar a ação Esquivar como ação bônus no seu turno.",
  },
  {
    id: "monge_passo_do_vento",
    nome: "Passo do Vento",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 2,
    tipoAcao: "Ação Bônus",
    recarga: "Descanso Curto",
    usosMax: "PONTOS_CHI",
    descricao: "Gasta 1 ponto de Chi para realizar as ações Desengajar ou Disparar como ação bônus, e sua distância de salto é dobrada.",
  },
  {
    id: "monge_movimento_sem_armadura",
    nome: "Movimento sem Armadura",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 2,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Seu deslocamento aumenta em +3m a +9m enquanto não estiver vestindo armadura nem empunhando escudo.",
  },
  {
    id: "monge_deflexao_projeteis",
    nome: "Deflexão de Projéteis",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 3,
    tipoAcao: "Reação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Reduz o dano de um projétil em 1d10 + Des + Nível de Monge. Se reduzir a 0 e tiver mão livre, pode pegar o projétil e arremessar (1 Chi).",
  },
  {
    id: "monge_queda_lenta",
    nome: "Queda Lenta",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 4,
    tipoAcao: "Reação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você pode usar sua reação quando cair para reduzir o dano da queda por um montante igual a 5 vezes seu nível de monge.",
  },
  {
    id: "monge_ataque_extra",
    nome: "Ataque Extra (Monge)",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você pode atacar duas vezes ao realizar a ação de Ataque no seu turno.",
  },
  {
    id: "monge_ataque_atordoante",
    nome: "Ataque Atordoante",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 5,
    tipoAcao: "Especial",
    recarga: "Descanso Curto",
    usosMax: "PONTOS_CHI",
    descricao: "Ao acertar golpe corpo a corpo, gasta 1 ponto de Chi; o alvo faz teste de Con ou fica atordoado até o fim do seu próximo turno.",
  },
  {
    id: "monge_golpes_chi",
    nome: "Golpes Fortalecidos por Chi",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 6,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Seus ataques desarmados contam como armas mágicas para vencer resistências e imunidades.",
  },
  {
    id: "monge_evasao",
    nome: "Evasão (Monge)",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 7,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Em testes de Destreza para metade do dano, você não sofre nenhum dano se passar e apenas metade se falhar.",
  },
  {
    id: "monge_mente_tranquila",
    nome: "Mente Tranquila",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 7,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você pode usar sua ação para encerrar um efeito em si mesmo que esteja lhe causando as condições enfeitiçado ou amedrontado.",
  },
  {
    id: "monge_pureza_corporal",
    nome: "Pureza Corporal",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 10,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Seu domínio do Chi o torna imune a doenças e venenos.",
  },
  {
    id: "monge_idioma_sol_lua",
    nome: "Idioma do Sol e da Lua",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 13,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você compreende todos os idiomas falados e qualquer criatura que entenda um idioma pode compreender o que você fala.",
  },
  {
    id: "monge_alma_diamante",
    nome: "Alma de Diamante",
    categoria: "classe",
    vinculo: "Monge",
    nivel: 14,
    tipoAcao: "Passiva",
    recarga: "Descanso Curto",
    usosMax: "PONTOS_CHI",
    descricao: "Você ganha proficiência em todos os testes de resistência. Além disso, pode gastar 1 Chi para rerrolar uma salvaguarda falha.",
  },

  // --- BRUXO ---
  {
    id: "bruxo_patrono",
    nome: "Patrono Transcendental",
    categoria: "classe",
    vinculo: "Bruxo",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você firma um pacto com uma entidade transcendental (Arquifada, Corruptor, Grande Antigo, etc.) que concede habilidades exclusivas.",
  },
  {
    id: "bruxo_magia_pacto",
    nome: "Magia de Pacto",
    categoria: "classe",
    vinculo: "Bruxo",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Descanso Curto",
    usosMax: null,
    descricao: "Seus espaços de magia são limitados mas sempre conjurados no círculo mais alto disponível e recarregam com Descanso Curto.",
  },
  {
    id: "bruxo_invocacoes_misticas",
    nome: "Invocações Místicas",
    categoria: "classe",
    vinculo: "Bruxo",
    nivel: 2,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Fragmentos de conhecimento proibido que concedem habilidades e magias permanentes à vontade.",
  },
  {
    id: "bruxo_dadiva_pacto",
    nome: "Dádiva do Pacto",
    categoria: "classe",
    vinculo: "Bruxo",
    nivel: 3,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Seu patrono lhe concede uma dádiva especial: Pacto da Corrente (familiar), Pacto da Lâmina (arma mágica) ou Pacto do Tomo (grimório).",
  },
  {
    id: "bruxo_arcano_mistico",
    nome: "Arcano Místico",
    categoria: "classe",
    vinculo: "Bruxo",
    nivel: 11,
    tipoAcao: "1 Ação",
    recarga: "Descanso Longo",
    usosMax: 1,
    descricao: "Seu patrono lhe confere um segredo mágico chamado arcano. Escolha uma magia de 6º círculo da lista de magias de bruxo (7º no nvl 13, 8º no nvl 15, 9º no nvl 17).",
  },

  // --- FEITICEIRO ---
  {
    id: "feiticeiro_origem_feiticaria",
    nome: "Origem da Feitiçaria",
    categoria: "classe",
    vinculo: "Feiticeiro",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "A fonte do seu poder inato (Linhagem Dracônica, Magia Selvagem, Alma Divina, etc.).",
  },
  {
    id: "feiticeiro_conjuracao",
    nome: "Conjuração de Feiticeiro",
    categoria: "classe",
    vinculo: "Feiticeiro",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Conjura magias inatas utilizando Carisma como atributo de conjuração.",
  },
  {
    id: "feiticeiro_fonte_magia",
    nome: "Fonte de Magia (Pontos de Feitiçaria)",
    categoria: "classe",
    vinculo: "Feiticeiro",
    nivel: 2,
    tipoAcao: "Ação Bônus",
    recarga: "Descanso Longo",
    usosMax: "PONTOS_FEITICARIA",
    descricao: "Reserva de Pontos de Feitiçaria igual ao nível de feiticeiro. Permite converter pontos em espaços de magia e vice-versa.",
  },
  {
    id: "feiticeiro_metamagica",
    nome: "Metamágica",
    categoria: "classe",
    vinculo: "Feiticeiro",
    nivel: 3,
    tipoAcao: "Especial",
    recarga: "Descanso Longo",
    usosMax: "PONTOS_FEITICARIA",
    descricao: "Distorce magias consumindo Pontos de Feitiçaria (ex: Magia Acelerada, Sutil, Duplicada, Potencializada).",
  },
  {
    id: "feiticeiro_restauracao",
    nome: "Restauração Feiticeira",
    categoria: "classe",
    vinculo: "Feiticeiro",
    nivel: 20,
    tipoAcao: "Passiva",
    recarga: "Descanso Curto",
    usosMax: null,
    descricao: "Você recupera 4 pontos de feitiçaria gastos sempre que terminar um descanso curto.",
  },

  // --- MAGO ---
  {
    id: "mago_conjuracao",
    nome: "Conjuração de Mago",
    categoria: "classe",
    vinculo: "Mago",
    nivel: 1,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Conjura magias do seu grimório utilizando Inteligência como atributo de conjuração.",
  },
  {
    id: "mago_recuperacao_arcana",
    nome: "Recuperação Arcana",
    categoria: "classe",
    vinculo: "Mago",
    nivel: 1,
    tipoAcao: "Especial",
    recarga: "Descanso Longo",
    usosMax: 1,
    descricao: "1x ao dia em descanso curto recupera espaços de magia cuja soma dos níveis seja menor ou igual a metade do nível de mago (arredondado para cima).",
  },
  {
    id: "mago_tradicao_arcana",
    nome: "Tradição Arcana (Escola de Magia)",
    categoria: "classe",
    vinculo: "Mago",
    nivel: 2,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Especialização em uma das 8 escolas arcanas (Evocação, Abjuração, Necromancia, Ilusão, etc.).",
  },
  {
    id: "mago_maestria_magia",
    nome: "Maestria em Magia",
    categoria: "classe",
    vinculo: "Mago",
    nivel: 18,
    tipoAcao: "Especial",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Escolha uma magia de 1º e uma de 2º nível do seu grimório. Você pode conjurá-las no seu menor círculo sem gastar espaços de magia.",
  },
  {
    id: "mago_assinatura_magia",
    nome: "Assinatura de Magia",
    categoria: "classe",
    vinculo: "Mago",
    nivel: 20,
    tipoAcao: "Especial",
    recarga: "Descanso Curto",
    usosMax: 2,
    descricao: "Escolha duas magias de 3º nível do seu grimório como suas assinaturas. Você pode conjurar cada uma 1x por descanso curto sem gastar espaço.",
  },

  // --- PATRULHEIRO ---
  {
    id: "patrulheiro_inimigo_favorito",
    nome: "Inimigo Favorito",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "+2 de dano em ataques com armas contra o tipo de criatura escolhido e vantagem em testes de Sobrevivência para rastreá-los.",
  },
  {
    id: "patrulheiro_explorador_natural",
    nome: "Explorador Natural",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 1,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Ignora terreno difícil, ganha vantagem em iniciativa e no primeiro turno tem vantagem em ataques contra quem ainda não agiu.",
  },
  {
    id: "patrulheiro_estilo_luta",
    nome: "Estilo de Luta (Patrulheiro)",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 2,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você adota um estilo de combate particular (Arquearia, Defesa, Duelo ou Luta com Duas Armas).",
  },
  {
    id: "patrulheiro_conjuracao",
    nome: "Conjuração de Patrulheiro",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 2,
    tipoAcao: "1 Ação",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Capacidade de conjurar magias de patrulheiro utilizando Sabedoria como atributo de conjuração.",
  },
  {
    id: "patrulheiro_consciencia_primitiva",
    nome: "Consciência Primitiva",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 3,
    tipoAcao: "1 Ação",
    recarga: "Descanso Longo",
    usosMax: "MOD_SAB",
    descricao: "Você pode gastar 1 espaço de magia para sentir a presença de aberrações, celestiais, dragões, elementais, fadas, corruptores e mortos-vivos a até 1,5 km.",
  },
  {
    id: "patrulheiro_ataque_extra",
    nome: "Ataque Extra (Patrulheiro)",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 5,
    tipoAcao: "Passiva",
    recarga: "Nenhum",
    usosMax: null,
    descricao: "Você pode atacar duas vezes ao invés de uma sempre que realizar a ação de Ataque.",
  },
  {
    id: "patrulheiro_passo_terra",
    nome: "Passo da Terra",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 8,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Mover-se através de terreno difícil não-mágico não custa movimento adicional.",
  },
  {
    id: "patrulheiro_esconder_vista",
    nome: "Esconder-se em Plena Vista",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 10,
    tipoAcao: "Especial",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você pode gastar 1 minuto criando camuflagem para obter +10 de bônus em testes de Furtividade enquanto permanecer imóvel.",
  },
  {
    id: "patrulheiro_desaparecer",
    nome: "Desaparecer",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 14,
    tipoAcao: "Ação Bônus",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Você pode usar a ação Esconder como ação bônus no seu turno, e não pode ser rastreado por meios não-mágicos.",
  },
  {
    id: "patrulheiro_sentidos_selvagens",
    nome: "Sentidos Selvagens",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 18,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "Ao atacar uma criatura que você não possa ver, sua incapacidade de enxergá-la não impõe desvantagem em suas jogadas de ataque contra ela.",
  },
  {
    id: "patrulheiro_matador_inimigos",
    nome: "Matador de Inimigos",
    categoria: "classe",
    vinculo: "Patrulheiro",
    nivel: 20,
    tipoAcao: "Passiva",
    recarga: "Ilimitado",
    usosMax: null,
    descricao: "1x em cada um dos seus turnos, você pode adicionar seu modificador de Sabedoria na jogada de ataque ou de dano contra um dos seus Inimigos Favoritos.",
  },
];

// ==========================================
// 🔍 FUNÇÕES AUXILIARES DE BUSCA E CÁLCULO
// ==========================================

/**
 * Retorna TODAS as habilidades da raça e TODA a árvore da classe (Níveis 1 a 20) para o Compêndio
 */
export function getCompendioProgressao(ficha) {
  if (!ficha) return [];

  const racaNorm = normalizeString(ficha.raca);
  const subracaNorm = normalizeString(ficha.subraca || ficha.DetalhesDaRaça?.SubRaca);
  const classeNorm = normalizeString(ficha.classe);
  const subclasseNorm = normalizeString(ficha.subclasse);
  const nivelAtual = Number(ficha.nivel || ficha.level) || 1;

  // Filtra e enriquece traços raciais
  const raciais = HABILIDADES_RACIAIS.filter((h) => {
    const v = normalizeString(h.vinculo);
    if (!v) return false;
    const matchRaca = racaNorm && (racaNorm.includes(v) || v.includes(racaNorm));
    const matchSubraca = subracaNorm && (subracaNorm.includes(v) || v.includes(subracaNorm));
    return matchRaca || matchSubraca;
  }).map((h) => ({
    ...h,
    categoria: h.categoria || "raca",
    origem: "raca",
    adquirida: true,
    desbloqueado: true,
    origemLabel: `Raça (${h.vinculo})`,
    subOrigem: h.vinculo || "Raça",
  }));

  // Filtra e enriquece recursos de classe (Níveis 1 ao 20)
  const deClasse = HABILIDADES_CLASSES.filter((h) => {
    const v = normalizeString(h.vinculo);
    if (!v) return false;
    const matchClasse = classeNorm && (classeNorm.includes(v) || v.includes(classeNorm));
    const matchSubclasse = subclasseNorm && (subclasseNorm.includes(v) || v.includes(subclasseNorm));
    return matchClasse || matchSubclasse;
  }).map((h) => {
    const isAdquirida = Number(h.nivel || 1) <= nivelAtual;
    return {
      ...h,
      categoria: h.categoria || "classe",
      origem: "classe",
      adquirida: isAdquirida,
      desbloqueado: isAdquirida,
      origemLabel: `${h.vinculo} (Nível ${h.nivel})`,
      subOrigem: `${h.vinculo} (Nvl ${h.nivel})`,
    };
  });

  // Habilidades personalizadas / livres / talentos
  const livres = (ficha.habilidadesLivres || []).map((h) => ({
    ...h,
    categoria: "livre",
    origem: "talento",
    adquirida: true,
    desbloqueado: true,
    origemLabel: "Talento / Livre",
    subOrigem: h.subOrigem || h.vinculo || "Talento / Livre",
    nivel: Number(h.nivel || h.level || 1),
    tipoAcao: h.tipoAcao || "Passiva",
  }));

  return [...raciais, ...deClasse, ...livres];
}

/**
 * Retorna apenas as habilidades ativas/desbloqueadas no nível atual do personagem
 */
export function getHabilidadesAtivas(ficha) {
  if (!ficha) return [];
  const full = getCompendioProgressao(ficha);
  return full.filter((h) => h.adquirida);
}

// Aliases para retrocompatibilidade
export const getHabilidadesPersonagem = (ficha, incluirFuturas = false) => {
  return incluirFuturas ? getCompendioProgressao(ficha) : getHabilidadesAtivas(ficha);
};
export const getCompendioCompleto = (ficha) => getCompendioProgressao(ficha);

/**
 * Calcula o valor numérico de usos máximos para rastreadores de combate
 */
export function calcularUsosMaximos(habilidade, ficha) {
  if (!habilidade) return null;
  if (typeof habilidade.usosMax === "number") return habilidade.usosMax;
  if (!habilidade.usosMax) return null;

  const nivel = Number(ficha?.nivel) || 1;
  const carMod = Math.floor(((ficha?.atributos?.carisma || 10) - 10) / 2);
  const sabMod = Math.floor(((ficha?.atributos?.sabedoria || 10) - 10) / 2);
  const conMod = Math.floor(((ficha?.atributos?.constituicao || 10) - 10) / 2);
  const intMod = Math.floor(((ficha?.atributos?.inteligencia || 10) - 10) / 2);

  switch (habilidade.usosMax) {
    case "MOD_CAR":
      return Math.max(1, carMod);
    case "MOD_SAB":
      return Math.max(1, sabMod);
    case "MOD_CON":
      return Math.max(1, conMod);
    case "MOD_INT":
      return Math.max(1, intMod);
    case "1 + MOD_CAR":
      return Math.max(1, 1 + carMod);
    case "NIVEL_PALADINO * 5":
    case "NIVEL * 5":
      return nivel * 5;
    case "PONTOS_CHI":
    case "PONTOS_FEITICARIA":
      return nivel;
    case "TABELA_FURIA":
      if (nivel >= 20) return 999;
      if (nivel >= 17) return 6;
      if (nivel >= 12) return 5;
      if (nivel >= 6) return 4;
      if (nivel >= 3) return 3;
      return 2;
    case "CANALIZAR_DIVINDADE":
      if (nivel >= 18) return 3;
      if (nivel >= 6) return 2;
      return 1;
    case "TABELA_SURTO_ACAO":
      return nivel >= 17 ? 2 : 1;
    case "TABELA_INDOMAVEL":
      if (nivel >= 17) return 3;
      if (nivel >= 13) return 2;
      return 1;
    case "TABELA_FORMA_SELVAGEM":
      return nivel >= 20 ? 999 : 2;
    default:
      if (!isNaN(Number(habilidade.usosMax))) {
        return Number(habilidade.usosMax);
      }
      return null;
  }
}
